service: hello-serverless-rust-world
provider:
  name: aws
  runtime: rust
plugins:
  - serverless-rust
package:
  individually: true

functions:
  users:
    handler: users
    events:
      - http:
          path: /users
          method: get
      - http:
          path: /users
          method: post