service: hello-serverless-rust-world
provider:
  name: aws
  runtime: rust
plugins:
  - serverless-rust
package:
  individually: true

functions:
  users:
    handler: users
    events:
      - http:
          path: /users/{user_id}
          method: get
          request:
            parameters:
              paths:
                user_id: true
      - http:
          path: /users
          method: post